.add_ssh: &add_ssh |
  mkdir ~/.ssh
  echo $SSH_KEY > ~/.ssh/id_rsa
  chmod 600 ~/.ssh/id_rsa
  ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts


kind: pipeline
type: kubernetes
name: default

services:
  - name: postgres
    image: postgres
    ports:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

steps:
  - name: install_dependencies
    image: node:12
    commands:
      - npm ci
  - name: prisma_generate
    image: node:12
    commands:
      - export DATABASE_URL="postgresql://postgres:@localhost:5432/postgres?schema=public"
      - npx prisma2 migrate up --experimental
      - npx prisma2 generate
    depends_on: [install_dependencies, postgres]
  - name: lint
    image: node:12
    commands:
      - npm run format:check
    depends_on: [prisma_generate]
  - name: unit-test
    image: node:12
    commands:
      - npm run test:unit
    depends_on: [prisma_generate, postgres, lint]
  - name: integration-test
    image: node:12
    commands:
      - npm run test:integration
    depends_on: [unit-test]
  - name: build
    image: node:12
    commands:
      - npm run build
    depends_on: [integration-test]
  - name: documentation
    image: node:12
    commands:
      - npm run doc
      - *add_ssh
      - git fetch --tags
      - VERSION=$(git describe --abbrev=0 --tag | tr -d '\n')
      - git clone $DOC_REPOSITORY_URL doc-git
      - rm -rf doc-git/docs
      - mv docs/ doc-git/
      - |
        cd doc-git
        git add .
        git commit -m "Update doc $VERSION"
        git tag $VERSION
        git log
        git push
        git push origin --tags
    environment:
      DOC_REPOSITORY_URL:
        from_secret: DOC_REPOSITORY_URL
      SSH_KEY:
        from_secret: DOC_SSH_KEY
    depends_on: [integration-test]
  - name: docker
    image: banzaicloud/drone-kaniko
    settings:
      email: kedthunder@gmail.com
      dockerfile: ./Dockerfile
      registry: docker.pkg.github.com
      repo: ked57/mspr-user-api/api
      username:
        from_secret: GITHUB_USERNAME
      password:
        from_secret: GITHUB_TOKEN
      tags:
        - ${DRONE_COMMIT_SHA:0:8}
        - latest
    depends_on: [documentation]
  - name: rollout
    image: pabloclsn/kubectl-docker:latest
    commands:
      - cat .kube/deployment.yml | envsubst | kubectl apply -f -
    environment:
      DATABASE_URL:
        from_secret: DATABASE_URL
    depends_on: [docker]

  # - name: Semantical Versionning
  #   image: python:3.6
  #   commands:
  #     - mkdir ~/.ssh
  #     - echo $CI_SSH_KEY > ~/.ssh/id_rsa
  #     - pip install -r .semver/requirements.txt
  #     - python .semver/main.py
  #   environment:
  #     CI_REPOSITORY_URL:
  #       from_secret: CI_REPOSITORY_URL
  #     CI_SSH_KEY:
  #       from_secret: CI_SSH_KEY
  #   depends_on: [prisma_generate]
  #   when:
  #     branch:
  #     - master
  #     event: push
