kind: pipeline
type: kubernetes
name: default

service:
  - name: db
    image: postgres

steps:
  - name: install_dependencies
    image: node:12
    commands:
      - npm ci
  - name: prisma_generate
    image: node:12
    commands:
      - export DATABASE_URL=postgres
      - npx prisma2 migrate up --experimental
      - npx prisma2 generate
    depends_on: [install_dependencies]
  - name: lint
    image: node:12
    commands:
      - npm run format:check
    depends_on: [prisma_generate]
  - name: test
    image: node:12
    commands:
      - npm run test
    depends_on: [prisma_generate]
  - name: build
    image: node:12
    commands:
      - npm run build
    depends_on: [prisma_generate]
  # - name: Semantical Versionning
  #   image: python:3.6
  #   commands:
  #     - mkdir ~/.ssh
  #     - echo $CI_SSH_KEY > ~/.ssh/id_rsa
  #     - pip install -r .semver/requirements.txt
  #     - python .semver/main.py
  #   environment:
  #     CI_REPOSITORY_URL:
  #       from_secret: CI_REPOSITORY_URL
  #     CI_SSH_KEY:
  #       from_secret: CI_SSH_KEY
  #   depends_on: [prisma_generate]
  #   when:
  #     branch:
  #     - master
  #     event: push
