kind: pipeline
type: kubernetes
name: default

steps:
  - name: install_dependencies
    image: node:12
    commands:
      - npm ci
  - name: lint
    image: node:12
    commands:
      - npm run format:check
    depends_on: [install_dependencies]
  - name: test
    image: node:12
    commands:
      - npm run test
    depends_on: [install_dependencies]
  - name: build
    image: node:12
    commands:
      - npm run build
    depends_on: [install_dependencies]
  - name: Semantical Versionning
    image: python:3.6
    commands:
      - mkdir ~/.ssh
      - echo $CI_SSH_KEY > ~/.ssh/id_rsa
      - pip install -r .semver/requirements.txt
      - python .semver/main.py
    environment:
      CI_REPOSITORY_URL:
        from_secret: CI_REPOSITORY_URL
      CI_SSH_KEY:
        from_secret: CI_SSH_KEY
    depends_on: [install_dependencies]
    when:
      branch:
      - master
      event: push
